#!/usr/bin/env zsh

ZSH="$HOME/.oh-my-zsh"
ZSH_CUSTOM="$HOME/.omz-custom"

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=10"

zstyle ':omz:update' mode disabled
zstyle ':omz:alpha:lib:git' async-prompt no

plugins=(
  git
  zsh-autosuggestions
  direnv
)

source $ZSH/oh-my-zsh.sh

