#!/usr/bin/env zsh

ZSH="$HOME/.oh-my-zsh"
ZSH_CUSTOM="$HOME/.omz-custom"

ZSH_THEME="spaceship"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=10"

plugins=(
  git
  zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

